site:
  name: "OpenFav Test Site"
  description: "A test site for OpenFav integration"
  base: "/"
  trailingSlash: false

metadata:
  title: "OpenFav Test Page"
  description: "This is a test page for OpenFav integration"
  image: "/images/og-image.jpg"
  lang: "en"
  author: "Test Author"
  keywords: ["test", "openfav", "astro"]
  twitterCard: "summary_large_image"

i18n:
  enable: true
  defaultLocale: "en"
  locales: ["en", "it"]
  routingStrategy: "prefix-other-locales"

ui:
  theme: "light"
  themeColor: "#3B82F6"
  backgroundColor: "#FFFFFF"
  accentColor: "#10B981"
  fontFamily: "Inter, sans-serif"

analytics:
  enable: false
  googleAnalyticsId: ""
  plausibleDomain: ""
  googleTagManagerId: ""
  hotjarId: ""
